name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: |
          # Your deployment commands
          git checkout -b gh-pages
          git rm -rf .
          cp -r /path/to/your/build/output/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
